apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: injector
spec:
  selector:
    matchLabels:
      app: injector
  template:
    metadata:
      labels:
        app: injector
    spec:
      containers:
        - name: injector
          image: fabiogentili/injector-go
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo.default.svc.cluster.local:27017
              #value: mongodb://mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: injector
spec:
  selector:
    app: injector
  ports:
    - port: 80
      targetPort: 5000
